default_install_hook_types: ["pre-commit", "pre-push"]

exclude: >
    (?x)(
        LICENSE$
    )

repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      require_serial: true
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
    - id: lint-requirements
      name: lint-requirements
      entry: python -m tools.lint_requirements
      language: python
      files: requirements-.*\.txt$
      additional_dependencies: [packaging==21.3]
