on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Runs package test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version:
            - 3.11
            - 3.10
      - name: Install test requirements
        run: |
          pip install -r test-requirements.txt
      - name: Run mypy
        run: |
          mypy
      - name: Run pytest
        run: |
          pytest
